import {StyleSheet, Platform, Dimensions, StatusBar} from 'react-native';
import {theme} from '../services/Common/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  cardCover: {
    height: '50%',
    width: '100%',
  },
  countdownContainer: {
    left: 0,
    right: 0,
    top: '32%',
    borderRadius: 60,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    paddingHorizontal: 28,
    marginHorizontal: '10%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_1,
  },
  countdownItem: {
    alignItems: 'center',
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  countdownLabel: {
    fontSize: 12,
    lineHeight: 14,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  countdownvalue: {
    fontSize: 32,
    lineHeight: 40,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  companyInfoContainer: {
    marginTop: '-8%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: theme.APP_COLOR_1,
  },
  companyInfoContentContainer: {
    paddingBottom: '10%',
  },
  info: {
    paddingVertical: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoImage: {
    width: 80,
    height: 80,
    marginRight: 22,
  },
  compantTitle: {
    fontSize: 16,
    lineHeight: 24,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  tags: {
    marginTop: 9,
    flexDirection: 'row',
  },
  tag: {
    marginRight: 8,
    borderRadius: 30,
    paddingVertical: 5,
    paddingHorizontal: 10.5,
    backgroundColor: theme.COLORS.DARK_BLUE,
  },
  tagText: {
    fontSize: 12,
    lineHeight: 14,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  mainDivider: {
    height: 2,
    backgroundColor: theme.APP_COLOR_2,
  },

  button: {
    marginTop: 30,
    marginHorizontal: '10%',
  },
  buttonIcon: {
    marginRight: 10,
  },
  buttonOuter: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
  radius30: {
    borderRadius: 30,
  },
  gradientButtonInner: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
  },
  tcText: {
    padding: 38,
    fontSize: 16,
    lineHeight: 29,
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  actionContainer: {
    paddingHorizontal: 40,
  },
  radioButtonContainer: {
    paddingTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonText: {
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'left',
    paddingHorizontal: 16,
    textTransform: 'uppercase',
    color: theme.COLORS.SILVER,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  radioButtonTextLink: {
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'left',
    paddingHorizontal: 16,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    color: theme.COLORS.DARK_BLUE,
    textDecorationLine: 'underline',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },

  // Info Modal Styling
  infoModalContainer: {
    flex: 1,
    paddingTop: StatusBar.currentHeight || '10%',
  },
  infoModalContentContainer: {
    flex: 1,
    marginTop: '8%',
    borderRadius: 30,
    marginBottom: '11.2%',
    marginHorizontal: '4.5%',
    backgroundColor: theme.APP_COLOR_2,
  },
  header: {
    height: '18%',
    alignItems: 'center',
    borderBottomWidth: 2,
    paddingHorizontal: '1%',
    justifyContent: 'center',
    borderBottomColor: theme.COLORS.LIGHT_GREY,
  },
  headerTitle: {
    fontSize: 24,
    marginTop: 13,
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  infoContainerItems: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: '4.5%',
    width: Dimensions.get('screen').width * 0.91,
  },
  infoContainerItem: {
    paddingTop: '13%',
  },
  infoContentItemTitle: {
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  infoContentItemDescription: {
    fontSize: 12,
    lineHeight: 19,
    marginTop: '6%',
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '400' : 'normal',
  },
  bottomContainer: {
    flex: 1,
    marginBottom: '10%',
    paddingHorizontal: '9%',
    justifyContent: 'flex-end',
  },
  dots: {
    flexWrap: 'wrap',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: '2%',
    paddingVertical: '1.25%',
    marginVertical: '13.5%',
    justifyContent: 'center',
  },
  dotOuter: {
    width: 12,
    height: 12,
    elevation: 5,
    borderRadius: 15,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginHorizontal: '1.25%',
    shadowColor: theme.COLORS.BLACK,
    shadowOffset: {width: 0, height: 4},
    backgroundColor: theme.COLORS.PURPLE,
  },
  dotOuterActive: {
    width: 12,
    height: 12,
    elevation: 5,
    borderRadius: 15,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginHorizontal: '1.25%',
    shadowColor: theme.COLORS.BLACK,
    backgroundColor: theme.COLORS.GREY,
    shadowOffset: {width: 0, height: 4},
  },
  modalButtonGradient: {
    borderRadius: 30,
    marginVertical: '1.25%',
  },
  modalButton: {
    margin: 2,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },

  //RadioButton Styling
  radioButton: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
    borderColor: theme.COLORS.LIGHT_GREY,
  },
  radioButtonDot: {
    width: 16,
    height: 16,
    borderRadius: 25,
    backgroundColor: theme.APP_COLOR_2,
  },

  // TC Modal Styling
  tcModalContainer: {
    flex: 1,
    paddingTop: '30%',
  },
  tcModalContentContainer: {
    flex: 1,
    borderRadius: 30,
    backgroundColor: theme.APP_COLOR_1,
  },
  tcHeaderTitle: {
    margin: 40,
    fontSize: 16,
    lineHeight: 29,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  tcContainerItems: {
    alignItems: 'center',
    paddingBottom: '50%',
    paddingHorizontal: 40,
  },
  tcContainerItem: {
    paddingTop: 32,
  },
  tcContentItemTitle: {
    fontSize: 18,
    lineHeight: 17,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  tcContentItemDescription: {
    fontSize: 12,
    lineHeight: 20,
    marginTop: 20,
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '400' : 'normal',
  },
  tcCloseButtonContainer: {
    left: 0,
    right: 0,
    bottom: 0,
    height: '30%',
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    position: 'absolute',
    paddingBottom: '15%',
    justifyContent: 'flex-end',
  },
  tcCloseButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
});
