import {Platform, StyleSheet, StatusBar, Dimensions} from 'react-native';
import {theme} from '../services/Common/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: '5.5%',
    paddingHorizontal: '4.2%',
  },
  contentContainer: {
    paddingBottom: '5%',
  },
  listItemOuter: {
    shadowColor: theme.COLORS.BLACK,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    shadowOffset: {width: 0, height: 4},
    elevation: 5,
    borderRadius: 15,
    marginVertical: '1.25%',
    backgroundColor: theme.APP_COLOR_2,
  },
  radius15: {
    borderRadius: 15,
  },
  listItemInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5.4%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
  },
  itemTitle: {
    fontSize: 16,
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.PURPLE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },

  infoModalContainer: {
    flex: 1,
    backgroundColor: theme.APP_COLOR_1,
    paddingTop: StatusBar.currentHeight || '10%',
  },
  infoModalContentContainer: {
    flex: 1,
    marginTop: '8%',
    borderRadius: 30,
    marginBottom: '11.2%',
    marginHorizontal: '4.5%',
    backgroundColor: theme.APP_COLOR_2,
  },
  header: {
    height: '14%',
    alignItems: 'center',
    borderBottomWidth: 2,
    paddingHorizontal: '1%',
    justifyContent: 'center',
    borderBottomColor: theme.COLORS.LIGHT_GREY,
  },
  headerTitle: {
    fontSize: 16,
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  infoContainerItems: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: '4.5%',
    width: Dimensions.get('screen').width * 0.91,
  },
  infoContainerItem: {
    paddingTop: '13%',
  },
  infoContentItemTitle: {
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  infoContentItemDescription: {
    fontSize: 12,
    lineHeight: 19,
    marginTop: '6%',
    textAlign: 'center',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '400' : 'normal',
  },
  bottomContainer: {
    flex: 1,
    marginBottom: '10%',
    paddingHorizontal: '9%',
    justifyContent: 'flex-end',
  },
  dots: {
    flexWrap: 'wrap',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: '2%',
    paddingVertical: '1.25%',
    marginVertical: '13.5%',
    justifyContent: 'center',
  },
  dotOuter: {
    width: 12,
    height: 12,
    elevation: 5,
    borderRadius: 15,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginHorizontal: '1.25%',
    shadowColor: theme.COLORS.BLACK,
    shadowOffset: {width: 0, height: 4},
    backgroundColor: theme.COLORS.PURPLE,
  },
  dotOuterActive: {
    width: 12,
    height: 12,
    elevation: 5,
    borderRadius: 15,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginHorizontal: '1.25%',
    shadowColor: theme.COLORS.BLACK,
    backgroundColor: theme.COLORS.GREY,
    shadowOffset: {width: 0, height: 4},
  },
  dotInner: {
    paddingVertical: '5.4%',
    paddingHorizontal: '1%',
  },
  buttonOuter: {
    shadowColor: theme.COLORS.BLACK,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    shadowOffset: {width: 0, height: 4},
    elevation: 5,
    borderRadius: 30,
    marginVertical: '1.25%',
    backgroundColor: theme.APP_COLOR_2,
  },
  radius30: {
    borderRadius: 30,
  },
  buttonInner: {
    margin: 2,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
});
