import {StyleSheet, Platform} from 'react-native';
import {theme} from '../services/Common/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  imageContainer: {
    marginTop: 5,
    borderWidth: 3,
    borderRadius: 250,
    borderColor: theme.COLORS.DARK_PURPLE,
  },
  image: {
    width: 120,
    height: 120,
    borderRadius: 250,
  },
  levelContainer: {
    top: 10,
    left: 10,
    right: 10,
    position: 'absolute',
    alignItems: 'center',
  },
  levelChip: {
    borderRadius: 30,
    paddingVertical: 3,
    paddingHorizontal: 10,
    backgroundColor: theme.APP_COLOR_2,
  },
  levelText: {
    fontSize: 9,
    lineHeight: 10,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  titleContainer: {
    marginTop: 10,
  },
  title: {
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  subTitle: {
    fontSize: 12,
    lineHeight: 20,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '400' : 'bold',
  },
  progressContainer: {
    marginTop: 20,
  },
  progressChip: {
    borderRadius: 30,
    paddingVertical: 5,
    paddingHorizontal: 30,
    backgroundColor: theme.COLORS.DARK_PURPLE,
  },
  progressText: {
    fontSize: 16,
    lineHeight: 19,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  doneText: {
    fontSize: 36,
    lineHeight: 41,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  divider: {
    height: 2,
    width: '100%',
    marginVertical: 20,
    backgroundColor: theme.APP_COLOR_2,
  },
  dividerCompleted: {
    height: 2,
    width: '100%',
    marginVertical: 20,
    backgroundColor: theme.COLORS.DARK_PURPLE,
  },
  dividerShadow: {
    left: 0,
    right: 0,
    bottom: 0,
    height: 70,
    opacity: 0.5,
    position: 'absolute',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  statusContainer: {
    alignItems: 'center',
    paddingHorizontal: '4%',
    justifyContent: 'center',
  },
  statusTitle: {
    fontSize: 24,
    lineHeight: 26,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  statusDescription: {
    fontSize: 16,
    marginTop: 15,
    lineHeight: 26,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  completedDescription: {
    fontSize: 16,
    lineHeight: 26,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  rewardContainer: {
    marginTop: 15,
  },
  expContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
  },
  rewardValue: {
    fontSize: 48,
    lineHeight: 55,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  rewardLabel: {
    fontSize: 18,
    marginLeft: 5,
    lineHeight: 21,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  rewardSign: {
    fontSize: 35,
    marginRight: 8,
    borderRadius: 25,
    paddingVertical: 5,
    overflow: 'hidden',
    textAlign: 'center',
    paddingHorizontal: 15,
    color: theme.APP_COLOR_1,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    backgroundColor: theme.COLORS.YELLOW,
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  xLabel: {
    fontSize: 10,
    lineHeight: 21,
    marginRight: 5,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },

  actionsContainer: {
    marginTop: 15,
  },
  button: {
    marginTop: 10,
  },
  buttonIcon: {
    marginRight: 10,
  },
  buttonIconImage: {
    width: 26,
    height: 20,
    marginRight: 10,
  },
  buttonOuter: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
  radius30: {
    borderRadius: 30,
  },
  gradientButtonInner: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
  },
  gradientButtonInnerDisabled: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
    backgroundColor: theme.COLORS.MID_GREY,
  },
  buttonText: {
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
  },
  closeButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
});
