import {StyleSheet, Platform, Dimensions} from 'react-native';
import {theme} from '../services/Common/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: '4%',
  },
  tabs: {
    marginTop: 33,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  tab: {
    padding: 10,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    width: Dimensions.get('window').width * 0.43,
  },
  tabActive: {
    backgroundColor: theme.APP_COLOR_2,
  },
  tabText: {
    fontSize: 16,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  emptyContainer: {
    padding: 35,
    marginTop: 23,
    borderWidth: 3,
    borderRadius: 16,
    alignItems: 'center',
    borderStyle: 'dashed',
    justifyContent: 'center',
    borderColor: theme.APP_COLOR_2,
  },
  emptyTitle: {
    fontSize: 16,
    lineHeight: 23,
    textAlign: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    color: theme.COLORS.GREY_80P,
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  emptyDescription: {
    fontSize: 10,
    marginTop: 20,
    lineHeight: 16,
    textAlign: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    color: theme.COLORS.GREY_80P,
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  buttonOuter: {
    width: '90%',
    alignSelf: 'center',
    marginTop: 30,
    shadowColor: theme.COLORS.BLACK,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    shadowOffset: {width: 0, height: 4},
    elevation: 5,
    borderRadius: 30,
  },
  gradientButtonInner: {
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
  },
  buttonIcon: {
    width: 14,
    height: 21,
  },
  missionCards: {
    paddingTop: 15,
  },
  missionCardsContentContainer: {
    paddingBottom: 25,
  },
  missionCard: {
    marginTop: 8,
    borderRadius: 15,
    paddingVertical: 20,
    flexDirection: 'row',
    paddingHorizontal: 18,
    backgroundColor: theme.APP_COLOR_2,
  },
  cardImage: {
    width: 88,
    height: 88,
    borderRadius: 250,
  },
  levelContainer: {
    top: 10,
    left: 10,
    right: 10,
    position: 'absolute',
    alignItems: 'center',
  },
  levelChip: {
    borderRadius: 30,
    paddingVertical: 3,
    paddingHorizontal: 10,
    backgroundColor: theme.APP_COLOR_2,
  },
  levelText: {
    fontSize: 9,
    lineHeight: 10,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  cardInfoContainer: {
    flex: 1,
    marginTop: 3,
    marginLeft: 10,
  },
  cardTitle: {
    fontSize: 12,
    lineHeight: 14,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  uploadTypeChip: {
    marginTop: 5,
    borderRadius: 30,
    paddingVertical: 2,
    paddingHorizontal: 12,
    alignSelf: 'flex-start',
    backgroundColor: theme.COLORS.DARK_PURPLE,
  },
  verifyTypeChip: {
    marginTop: 5,
    borderRadius: 30,
    paddingVertical: 2,
    paddingHorizontal: 12,
    alignSelf: 'flex-start',
    backgroundColor: theme.COLORS.DARK_BLUE,
  },
  typeText: {
    fontSize: 8,
    lineHeight: 10,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  statusContainer: {
    marginTop: 20,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressText: {
    fontSize: 16,
    lineHeight: 18,
    marginLeft: 5,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  pendingText: {
    fontSize: 12,
    lineHeight: 14,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    color: theme.COLORS.WHITE_OPACITY_40P,
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  rewardButton: {
    height: 40,
    borderRadius: 60,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    justifyContent: 'center',
    backgroundColor: theme.COLORS.SUCCESS_COLOR,
  },
  rewardButtonDisabled: {
    height: 40,
    borderRadius: 60,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    justifyContent: 'center',
    backgroundColor: theme.COLORS.MID_GREY,
  },
});
