import {StyleSheet, processColor, Platform, Dimensions} from 'react-native';
import {theme} from '../services/Common/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: '5.5%',
    paddingHorizontal: '4.2%',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  tabOuter: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    width: Dimensions.get('window').width * 0.4,
  },
  tabOuterActive: {
    backgroundColor: theme.APP_COLOR_2,
  },
  tabInner: {
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabText: {
    fontSize: 10,
    lineHeight: 11.5,
    textAlign: 'center',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'normal',
  },
  tabTextActive: {
    fontSize: 12,
    lineHeight: 13.8,
  },
  statsContainer: {
    borderRadius: 8,
    backgroundColor: theme.APP_COLOR_2,
  },
  uavContainer: {
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
  },
  uavItem: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uavCenterItem: {
    width: '40%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uavItemDivider: {
    width: 1,
    height: '105%',
    marginTop: -22,
    marginBottom: -45,
    backgroundColor: theme.APP_COLOR_1,
  },
  imageIcon: {
    height: 30,
    width: 30,
  },
  uavItemTitle: {
    fontSize: 10,
    marginTop: 9,
    lineHeight: 12,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '400' : 'normal',
  },
  uavItemValue: {
    fontSize: 13,
    marginTop: 10,
    lineHeight: 15,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '600' : 'normal',
  },
  uavItemQuicraValue: {
    fontSize: 9,
    marginTop: 34,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '600' : 'normal',
  },
  uavItemQuicra: {
    fontSize: 6,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '300' : 'normal',
  },
  uavStatsDivider: {
    height: 1,
    backgroundColor: theme.APP_COLOR_1,
  },
  quicraContainer: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quicraValue: {
    fontSize: 17,
    lineHeight: 20.57,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '600' : 'bold',
  },
  quicra: {
    fontSize: 6,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '300' : 'normal',
  },
  mainDivider: {
    height: 2,
    marginVertical: 29,
    marginHorizontal: -15,
    backgroundColor: theme.APP_COLOR_2,
  },
  graph: {
    fontSize: 18,
    marginBottom: 10,
    lineHeight: 20.71,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  graphContainer: {
    borderRadius: 8,
    marginTop: 22,
    paddingVertical: 12,
    paddingHorizontal: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
  graphTitle: {
    fontSize: 11,
    lineHeight: 13,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  graphQuicra: {
    fontSize: 6,
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    fontFamily: 'Inter-Regular',
    fontWeight: Platform.OS === 'ios' ? '300' : 'normal',
  },
});
